### ISSUE TITLE
E2 - Arquitetura da Solução

### ISSUE THREAD

**Issue by RafaelCsza** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#10]
- [x] Gerar imagem com a Arquitetura do Software (Confirmar com professor)
- [x] Diagrama de Classes - Incluir Classe Crud @LucasCdeAbreu 
- [x] Modelo ER  @Rafael-Csza 
- [x] Esquema Relacional @Rafael-Csza 
- [x]  Modelo Físico @Rafael-Csza 
- [x] Descrever tecnologias utilizadas (verificar com o prof. se é necessário, pois já tem em Meteodologia)
- [x] Descrever Hospedagem 
- [x] Descrever sub-características de Qualidade utilizadas (verificar com o prof. se é necessário)
- [x] Adicionar contexto em 05 _Diagrama de Classes_, _Modelo ER_ @willamsandradelima

**Comment by willamsandradelima** [comment]
A confirmar com o professor em 03/04
- Confirmar quais itens são entregáveis da Etapa 2
- Definição do professor para "Projeto de Base de Dados" para alinhar fechamento ou não da issue do Todo
