### ISSUE TITLE
E1 - Especificação do Projeto

### ISSUE THREAD

**Issue by LucasCdeAbreu** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#12]
Revisar se o texto está atualizado, conforme texto do Teams:
- [x] Personas. Precisamos colocar as imagens das personas na documentação do Git ? @willamsandradelima 
- [x] Histórias de usuários
- [x] Requisitos funcionais e não funcionais
- [x] Restrições

- [x] Criar Diagrama de Casos de Uso @LucasCdeAbreu 
- [x] Fazer Upload do Diagrama de Casos de Uso no GitHub e Teams @LucasCdeAbreu

**Comment by willamsandradelima** [comment]
A confirmar com o professor em 03/04:
- _Verificar se é necessário incluir no texto: Modelagem do Processo de Negócio, Indicadores de Desempenho , Matriz de Rastreabilidade e Gerenciamento do Projeto_
