### ISSUE TITLE
E1 - Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#2]
- [x] Desenhar (Astah UML)
- [x] Salvar imagens no texto
- [x] Carregar no Git
- [x] Ajustar setas do includ e extend

**Comment by LucasCdeAbreu** [comment]
Diagrama de Casos de Uso atualizado. Novo arquivo .asta em https://sgapucminasbr.sharepoint.com/:u:/r/sites/GrupoD478/Documentos%20Compartilhados/General/PUConstruir/DiagramaCasosUso/Use%20Case%20Diagram%20PUConstruir.asta?csf=1&web=1&e=671g9F
