### ISSUE TITLE
E2 - Projeto da Interface

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#7]
- [x] Wireframes (Imagens) @Rafael-Csza 
- [x] Wireframes Interativos @Rafael-Csza 
- [x] Fazer upload dos Wireframes imagens e Interativos no Github dentro do documento, conectando no texto cada um ao Requisito atendido. @Rafael-Csza. @willamsandradelima pode ajudar nisto! 

- [x] Diagrama de Fluxo @LucasCdeAbreu  
- [x] Adicionar contexto em 04 _Diagrama de Fluxo_, _Wireframes_ @willamsandradelima em 05.04.2024
- [ ] _Bem vindo_ para _**Bem-vindo**_ nos wireframes.

**Comment by willamsandradelima** [comment]
@Rafael-Csza precisamos escrever texto explicativo dos wireframes no item "4-Projeto de Interface"?
