### ISSUE TITLE
E2 - Plano de Testes

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#8]
Plano de testes de software @willamsandradelima 
- [x] CT-01 para RF-01
- [x] CT-02 para RF-01
- [x] CT-03 para RF-02
- [x] CT-04 para RF-03
- [x] CT-05 para RF-03
- [x] CT-06 para RF-03
- [x] CT-07 para RF-04
- [x] CT-08 para RF-04
- [x] CT-09 para RF-04
- [x] CT-10 para RF-05
- [x] CT-11 para RF-05
- [x] CT-12 para RF-05
- [x] CT-13 para RF-06
- [x] CT-14 para RF-07

**Comment by willamsandradelima** [comment]
O Plano de Teste de Software é gerado a partir da especificação do sistema e consiste em casos de testes que deverão ser executados quando a implementação estiver parcial ou totalmente pronta.

Neste momento apenas se planeja quais funcionalidades vão ser testadas e como.

O teste será executado nas sprints seguintes, quando os casos de uso forem implementados.

**Comment by willamsandradelima** [comment]
A confirmar com o professor em 03/04 se:
- _Preenchemos no item 08 o script_
