### ISSUE TITLE
E2 - Projeto da Base de Dados

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t7-puconstruir#9]
A ser confirmado com o professor em 03/04
- _Qual a definição dele para este item._

**Comment by LucasCdeAbreu** [comment]
Verificar se essa issue já está incluida na issue de Arquitetura da Solução

**Comment by willamsandradelima** [comment]
_O projeto da base de dados corresponde à representação das entidades e relacionamentos identificadas no Modelo ER, no formato de tabelas, com colunas e chaves primárias/estrangeiras necessárias para representar corretamente as restrições de integridade._

_Para mais informações, consulte o microfundamento "Modelagem de Dados"._
